### ISSUE TITLE
[Colab] Asking to run Step 1 even after running it

### ISSUE THREAD

**Issue by arthurcaio92** [anothermartz/Easy-Wav2Lip#29] opened 2024-03-14 12:21 UTC
Greetings!

I am trying to run the Colab version of the code. When I run Step 1 it finishes in about 1 and a half minutes but then when I run Step 2 I get a message saying the following:

**An exception has occurred, use %tb to see the full traceback.**

**SystemExit: Step 1 has not been run in this instance! Please run step 1 each time you disconnect from a runtime.
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.**
  **warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)**

Could you please help me fix this? I haven't changed anything in the code, I am just running it as is.

Thank you very much! Your code is great!

**Comment by anothermartz** [comment] 2024-03-14 14:30
Thank you for the detailed description of the problem, I'll have to give it a look when I get on my PC later today, it's probably just something that has updated somewhere and I need to adapt my code to how it now works.

This is the same issue as #28

**Comment by jaybatsby1** [comment] 2024-03-14 14:37
Thank you very much for your code. God bless you!
Hope you will find a solution :)

**Comment by Mishmallow11** [comment] 2024-03-14 23:21
@anothermartz Hello! Please tell me when the services will be ready for use, I would really like it as soon as possible. Thank you very much!

**Comment by anothermartz** [comment] 2024-03-15 22:46
Please see my new quick fix, it isn't ideal but it works until I find a better way around it:

https://github.com/anothermartz/Easy-Wav2Lip/releases/tag/v8_1_quickfix

Closing this thread as it is a duplicate of issue #28

**Closed as not planned by anothermartz** 2024-03-15 22:46 UTC
